// src/ui/qwik/AlapLink.tsx
/**
 * Copyright 2026 Daniel Smith
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  component$,
  useSignal,
  useVisibleTask$,
  useId,
  $,
  Slot,
  type QRL,
  type CSSProperties,
} from '@builder.io/qwik';
import { useAlapContext } from './context';
import type { AlapLink as AlapLinkType } from '../../core/types';
import { sanitizeUrl } from '../../core/sanitizeUrl';
import type { TriggerHoverDetail, TriggerContextDetail, ItemHoverDetail, ItemContextDetail, Placement } from '../shared';
import { calcPlacementState, applyPlacementToMenu, clearPlacementClass, observeTriggerOffscreen } from '../shared';
import {
  REM_PER_MENU_ITEM,
  DEFAULT_MENU_Z_INDEX,
  MENU_CONTAINER_CLASS,
  MENU_ITEM_CLASS,
  DEFAULT_LINK_TARGET,
} from '../../constants';

export type { TriggerHoverDetail, TriggerContextDetail, ItemHoverDetail, ItemContextDetail };
export type AlapLinkMode = 'dom' | 'popover';

export interface AlapLinkProps {
  query: string;
  anchorId?: string;
  mode?: AlapLinkMode;
  class?: string;
  menuClassName?: string;
  menuStyle?: CSSProperties;
  listType?: 'ul' | 'ol';
  maxVisibleItems?: number;
  onTriggerHover$?: QRL<(detail: TriggerHoverDetail) => void>;
  onTriggerContext$?: QRL<(detail: TriggerContextDetail) => void>;
  onItemHover$?: QRL<(detail: ItemHoverDetail) => void>;
  onItemContext$?: QRL<(detail: ItemContextDetail) => void>;
  placement?: Placement;
  gap?: number;
  padding?: number;
}

type ResolvedLink = { id: string } & AlapLinkType;

const WRAPPER_STYLE: CSSProperties = { position: 'relative', display: 'inline' };

const MENU_POSITION_DEFAULTS: CSSProperties = {
  position: 'absolute',
  top: '100%',
  left: '0',
  zIndex: String(DEFAULT_MENU_Z_INDEX),
};

export const AlapLink = component$<AlapLinkProps>((props) => {
  const ctx = useAlapContext();

  const isOpen = useSignal(false);
  const items = useSignal<ResolvedLink[]>([]);

  const triggerId = useId();
  const menuId = useId();

  const triggerRef = useSignal<HTMLSpanElement>();
  const menuRef = useSignal<HTMLDivElement>();
  const wrapperRef = useSignal<HTMLSpanElement>();
  const itemRefs = useSignal<HTMLAnchorElement[]>([]);

  const timerId = useSignal(0);

  const mode = props.mode ?? 'dom';
  const resolvedListType = props.listType ?? ctx.defaultListType;
  const resolvedMaxVisibleItems = props.maxVisibleItems ?? ctx.defaultMaxVisibleItems;

  const mergedMenuClassName = (() => {
    const parts = [MENU_CONTAINER_CLASS];
    if (ctx.defaultMenuClassName) parts.push(ctx.defaultMenuClassName);
    if (props.menuClassName) parts.push(props.menuClassName);
    return parts.join(' ');
  })();

  const mergedMenuStyle: CSSProperties = { ...MENU_POSITION_DEFAULTS, ...props.menuStyle };

  // --- Timer ---

  const stopTimer = $(() => {
    if (timerId.value) {
      clearTimeout(timerId.value);
      timerId.value = 0;
    }
  });

  const closeMenu = $(() => {
    isOpen.value = false;
    stopTimer();
    triggerRef.value?.focus();
  });

  const startTimer = $(() => {
    stopTimer();
    timerId.value = window.setTimeout(() => {
      isOpen.value = false;
      timerId.value = 0;
      triggerRef.value?.focus();
    }, ctx.menuTimeout);
  });

  // --- Open / close ---

  const openMenu = $(() => {
    if (!ctx.engine) return;
    const resolved = ctx.engine.resolve(props.query, props.anchorId);
    if (resolved.length === 0) return;
    items.value = resolved;
    isOpen.value = true;
  });

  const toggleMenu = $(() => {
    if (isOpen.value) closeMenu();
    else openMenu();
  });

  // --- Browser-only effects: dismissal, focus, placement ---

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ track, cleanup }) => {
    const open = track(() => isOpen.value);
    if (!open) return;

    // Focus first item
    requestAnimationFrame(() => {
      const firstItem = itemRefs.value[0];
      if (firstItem) {
        firstItem.focus();
        startTimer();
      }
    });

    // Click outside + escape (dom mode only)
    if (mode !== 'popover') {
      const handleClickOutside = (e: MouseEvent) => {
        const target = e.target as Node;
        if (
          menuRef.value && !menuRef.value.contains(target) &&
          triggerRef.value && !triggerRef.value.contains(target)
        ) {
          closeMenu();
        }
      };

      const handleEscape = (e: KeyboardEvent) => {
        if (e.key === 'Escape') closeMenu();
      };

      document.addEventListener('click', handleClickOutside);
      document.addEventListener('keydown', handleEscape);

      cleanup(() => {
        document.removeEventListener('click', handleClickOutside);
        document.removeEventListener('keydown', handleEscape);
      });
    }

    // Compass placement
    if (props.placement && mode !== 'popover') {
      const tEl = triggerRef.value;
      const mEl = menuRef.value;
      const wEl = wrapperRef.value;

      if (tEl && mEl && wEl) {
        const apply = () => {
          const state = calcPlacementState(tEl, mEl, {
            placement: props.placement!,
            gap: props.gap,
            padding: props.padding,
          });
          applyPlacementToMenu(mEl, wEl, state);
        };

        requestAnimationFrame(apply);

        const onScroll = () => apply();
        window.addEventListener('scroll', onScroll, { passive: true });

        cleanup(() => {
          window.removeEventListener('scroll', onScroll);
          clearPlacementClass(mEl);
        });
      }
    }

    // Trigger scroll-away detection
    if (mode !== 'popover' && triggerRef.value) {
      const observer = observeTriggerOffscreen(triggerRef.value, () => closeMenu());
      cleanup(() => observer.disconnect());
    }
  });

  // Popover toggle event
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup }) => {
    if (mode !== 'popover' || !menuRef.value) return;
    const el = menuRef.value;
    const onToggle = (e: Event) => {
      if ((e as ToggleEvent).newState === 'closed') {
        isOpen.value = false;
      }
    };
    el.addEventListener('toggle', onToggle);
    cleanup(() => el.removeEventListener('toggle', onToggle));
  });

  // Cleanup timer on unmount
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup }) => {
    cleanup(() => {
      if (timerId.value) clearTimeout(timerId.value);
    });
  });

  // --- Trigger handlers ---

  const handleTriggerClick = $((e: MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (mode === 'popover' && !isOpen.value) {
      openMenu();
    } else {
      toggleMenu();
    }
  });

  const handleTriggerKeyDown = $((e: KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      if (mode === 'popover' && !isOpen.value) {
        openMenu();
      } else {
        toggleMenu();
      }
    }
  });

  // --- Keyboard nav ---

  const handleMenuKeyDown = $((e: KeyboardEvent) => {
    const validItems = itemRefs.value.filter(Boolean);
    if (validItems.length === 0) return;

    const activeIndex = validItems.indexOf(document.activeElement as HTMLAnchorElement);

    switch (e.key) {
      case 'ArrowDown': {
        e.preventDefault();
        const next = activeIndex < validItems.length - 1 ? activeIndex + 1 : 0;
        validItems[next].focus();
        validItems[next].scrollIntoView({ block: 'nearest' });
        break;
      }
      case 'ArrowUp': {
        e.preventDefault();
        const prev = activeIndex > 0 ? activeIndex - 1 : validItems.length - 1;
        validItems[prev].focus();
        validItems[prev].scrollIntoView({ block: 'nearest' });
        break;
      }
      case 'Home':
        e.preventDefault();
        validItems[0].focus();
        validItems[0].scrollIntoView({ block: 'nearest' });
        break;
      case 'End':
        e.preventDefault();
        validItems[validItems.length - 1].focus();
        validItems[validItems.length - 1].scrollIntoView({ block: 'nearest' });
        break;
      case 'Escape':
      case 'Tab':
        closeMenu();
        break;
    }
  });

  // --- Scroll style for max visible items ---

  const scrollStyle: CSSProperties | undefined =
    resolvedMaxVisibleItems > 0 && items.value.length > resolvedMaxVisibleItems
      ? { maxHeight: `${resolvedMaxVisibleItems * REM_PER_MENU_ITEM}rem`, overflowY: 'auto' }
      : undefined;

  // --- Shared menu item renderer ---

  const renderItems = () =>
    items.value.map((item, i) => (
      <li
        key={item.id}
        role="none"
        class={item.cssClass ? `${MENU_ITEM_CLASS} ${item.cssClass}` : MENU_ITEM_CLASS}
      >
        <a
          ref={(el: Element) => { itemRefs.value[i] = el as HTMLAnchorElement; }}
          href={sanitizeUrl(item.url)}
          target={item.targetWindow ?? DEFAULT_LINK_TARGET}
          role="menuitem"
          tabIndex={-1}
          onMouseEnter$={props.onItemHover$
            ? $(() => props.onItemHover$!({ id: item.id, link: item, query: props.query }))
            : undefined}
          onContextMenu$={props.onItemContext$
            ? $((e: MouseEvent) => props.onItemContext$!({ id: item.id, link: item, query: props.query, event: e }))
            : undefined}
        >
          {item.image ? (
            <img src={sanitizeUrl(item.image)} alt={item.altText ?? `image for ${item.id}`} />
          ) : (
            item.label ?? item.id
          )}
        </a>
      </li>
    ));

  // --- Render ---

  const ListTag = resolvedListType;

  const triggerProps = {
    ref: triggerRef,
    role: 'button' as const,
    tabIndex: 0,
    'aria-haspopup': 'true' as const,
    'aria-expanded': isOpen.value,
    'aria-controls': isOpen.value ? menuId : undefined,
    class: props.class,
    onClick$: handleTriggerClick,
    onKeyDown$: handleTriggerKeyDown,
    onMouseEnter$: props.onTriggerHover$
      ? $(() => props.onTriggerHover$!({ query: props.query, anchorId: props.anchorId }))
      : undefined,
    onContextMenu$: props.onTriggerContext$
      ? $((e: MouseEvent) => props.onTriggerContext$!({ query: props.query, anchorId: props.anchorId, event: e }))
      : undefined,
  };

  const menuContainerProps = {
    ref: menuRef,
    id: menuId,
    role: 'menu' as const,
    'aria-labelledby': triggerId,
    class: mergedMenuClassName,
    style: mergedMenuStyle,
    onKeyDown$: handleMenuKeyDown,
    onMouseLeave$: startTimer,
    onMouseEnter$: stopTimer,
  };

  if (mode === 'popover') {
    return (
      <>
        <span {...triggerProps} {...{ popoverTarget: menuId } as Record<string, string>}>
          <Slot />
        </span>
        <div {...menuContainerProps} {...{ popover: 'auto' } as Record<string, string>}>
          {isOpen.value && (
            <ListTag role="presentation" style={scrollStyle}>
              {renderItems()}
            </ListTag>
          )}
        </div>
      </>
    );
  }

  return (
    <span ref={wrapperRef} style={WRAPPER_STYLE}>
      <span {...triggerProps}>
        <Slot />
      </span>
      {isOpen.value && (
        <div {...menuContainerProps}>
          <ListTag role="presentation" style={scrollStyle}>
            {renderItems()}
          </ListTag>
        </div>
      )}
    </span>
  );
});

// src/ui/solid/AlapLink.tsx
/**
 * Copyright 2026 Daniel Smith
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createSignal, createEffect, onCleanup, For, Show, type JSX } from 'solid-js';
import { Dynamic } from 'solid-js/web';
import { useAlapContext } from './context';
import type { AlapLink as AlapLinkType } from '../../core/types';
import { sanitizeUrl } from '../../core/sanitizeUrl';
import type { TriggerHoverDetail, TriggerContextDetail, ItemHoverDetail, ItemContextDetail, Placement } from '../shared';
import { calcPlacementState, applyPlacementToMenu, clearPlacementClass, observeTriggerOffscreen } from '../shared';
import { REM_PER_MENU_ITEM } from '../../constants';

export type { TriggerHoverDetail, TriggerContextDetail, ItemHoverDetail, ItemContextDetail };
export type AlapLinkMode = 'dom' | 'webcomponent' | 'popover';

export interface AlapLinkProps {
  query: string;
  anchorId?: string;
  mode?: AlapLinkMode;
  children: JSX.Element;
  class?: string;
  menuClassName?: string;
  menuStyle?: JSX.CSSProperties;
  listType?: 'ul' | 'ol';
  maxVisibleItems?: number;
  onTriggerHover?: (detail: TriggerHoverDetail) => void;
  onTriggerContext?: (detail: TriggerContextDetail) => void;
  onItemHover?: (detail: ItemHoverDetail) => void;
  onItemContext?: (detail: ItemContextDetail) => void;
  /** Compass placement (N, NE, E, SE, S, SW, W, NW, C). When set, uses the placement engine. */
  placement?: Placement;
  /** Pixel gap between trigger and menu edge. Default: 4. */
  gap?: number;
  /** Minimum pixel distance from viewport edges. Default: 8. */
  padding?: number;
}

type ResolvedLink = { id: string } & AlapLinkType;

let idCounter = 0;
function uid() {
  return `alap-${++idCounter}`;
}

export function AlapLink(props: AlapLinkProps) {
  const ctx = useAlapContext();

  const [isOpen, setIsOpen] = createSignal(false);
  const [items, setItems] = createSignal<ResolvedLink[]>([]);

  const triggerId = uid();
  const menuId = uid();

  let triggerEl: HTMLSpanElement | undefined;
  let menuEl: HTMLDivElement | undefined;
  let wrapperEl: HTMLSpanElement | undefined;
  const itemEls: HTMLAnchorElement[] = [];

  let timerId = 0;

  const mode = () => props.mode ?? 'dom';
  const resolvedListType = () => props.listType ?? ctx.defaultListType;
  const resolvedMaxVisibleItems = () => props.maxVisibleItems ?? ctx.defaultMaxVisibleItems;

  const mergedMenuClassName = () => {
    const parts = ['alapelem'];
    if (ctx.defaultMenuClassName) parts.push(ctx.defaultMenuClassName);
    if (props.menuClassName) parts.push(props.menuClassName);
    return parts.join(' ');
  };

  const menuPositionDefaults: JSX.CSSProperties = {
    position: 'absolute',
    top: '100%',
    left: '0',
    'z-index': '10',
  };

  const mergedMenuStyle = (): JSX.CSSProperties => {
    return { ...menuPositionDefaults, ...ctx.defaultMenuStyle, ...props.menuStyle };
  };

  // --- Timer ---

  function startTimer() {
    stopTimer();
    timerId = window.setTimeout(closeMenu, ctx.menuTimeout);
  }

  function stopTimer() {
    if (timerId) {
      clearTimeout(timerId);
      timerId = 0;
    }
  }

  // --- Open / close ---

  function openMenu() {
    const resolved = ctx.engine.resolve(props.query, props.anchorId);
    if (resolved.length === 0) return;
    setItems(resolved);
    setIsOpen(true);
  }

  function closeMenu() {
    setIsOpen(false);
    stopTimer();
    triggerEl?.focus();
  }

  function toggleMenu() {
    if (isOpen()) closeMenu();
    else openMenu();
  }

  // --- Focus first item on open ---

  createEffect(() => {
    if (isOpen() && itemEls[0]) {
      itemEls[0].focus();
      startTimer();
    }
  });

  // --- Click outside + Escape (dom/webcomponent modes) ---

  createEffect(() => {
    if (!isOpen() || mode() === 'popover') return;

    const handleClickOutside = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        menuEl && !menuEl.contains(target) &&
        triggerEl && !triggerEl.contains(target)
      ) {
        closeMenu();
      }
    };

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') closeMenu();
    };

    document.addEventListener('click', handleClickOutside);
    document.addEventListener('keydown', handleEscape);

    onCleanup(() => {
      document.removeEventListener('click', handleClickOutside);
      document.removeEventListener('keydown', handleEscape);
    });
  });

  // --- Popover toggle event ---

  createEffect(() => {
    if (mode() !== 'popover' || !menuEl) return;
    const el = menuEl;
    const onToggle = (e: Event) => {
      if ((e as ToggleEvent).newState === 'closed') {
        setIsOpen(false);
      }
    };
    el.addEventListener('toggle', onToggle);
    onCleanup(() => el.removeEventListener('toggle', onToggle));
  });

  // --- Compass placement ---

  createEffect(() => {
    if (!isOpen() || !props.placement || mode() === 'popover') return;
    if (!triggerEl || !menuEl || !wrapperEl) return;

    const tEl = triggerEl;
    const mEl = menuEl;
    const wEl = wrapperEl;
    const p = props.placement;

    const apply = () => {
      const state = calcPlacementState(tEl, mEl, {
        placement: p,
        gap: props.gap,
        padding: props.padding,
      });
      applyPlacementToMenu(mEl, wEl, state);
    };

    apply();

    const onScroll = () => apply();
    window.addEventListener('scroll', onScroll, { passive: true });

    onCleanup(() => {
      window.removeEventListener('scroll', onScroll);
      clearPlacementClass(mEl);
    });
  });

  // --- Trigger scroll-away detection ---

  createEffect(() => {
    if (!isOpen() || mode() === 'popover') return;
    if (!triggerEl) return;

    const observer = observeTriggerOffscreen(triggerEl, closeMenu);
    onCleanup(() => observer.disconnect());
  });

  // --- Cleanup timer on unmount ---

  onCleanup(stopTimer);

  // --- Keyboard nav ---

  function handleMenuKeyDown(e: KeyboardEvent) {
    const validItems = itemEls.filter(Boolean);
    if (validItems.length === 0) return;

    const activeIndex = validItems.indexOf(document.activeElement as HTMLAnchorElement);

    switch (e.key) {
      case 'ArrowDown': {
        e.preventDefault();
        const next = activeIndex < validItems.length - 1 ? activeIndex + 1 : 0;
        validItems[next].focus();
        validItems[next].scrollIntoView({ block: 'nearest' });
        break;
      }
      case 'ArrowUp': {
        e.preventDefault();
        const prev = activeIndex > 0 ? activeIndex - 1 : validItems.length - 1;
        validItems[prev].focus();
        validItems[prev].scrollIntoView({ block: 'nearest' });
        break;
      }
      case 'Home':
        e.preventDefault();
        validItems[0].focus();
        validItems[0].scrollIntoView({ block: 'nearest' });
        break;
      case 'End':
        e.preventDefault();
        validItems[validItems.length - 1].focus();
        validItems[validItems.length - 1].scrollIntoView({ block: 'nearest' });
        break;
      case 'Escape':
      case 'Tab':
        closeMenu();
        break;
    }
  }

  // --- Trigger handlers ---

  function handleTriggerClick(e: MouseEvent) {
    e.preventDefault();
    e.stopPropagation();
    if (mode() === 'popover' && !isOpen()) {
      openMenu();
    } else {
      toggleMenu();
    }
  }

  function handleTriggerKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      if (mode() === 'popover' && !isOpen()) {
        openMenu();
      } else {
        toggleMenu();
      }
    }
  }

  // --- Scroll style for max visible items ---

  const scrollStyle = (): JSX.CSSProperties | undefined => {
    const max = resolvedMaxVisibleItems();
    if (max > 0 && items().length > max) {
      return { 'max-height': `${max * REM_PER_MENU_ITEM}rem`, 'overflow-y': 'auto' };
    }
    return undefined;
  };

  // --- Menu list ---

  function MenuList() {
    itemEls.length = 0;

    return (
      <Dynamic component={resolvedListType()} role="presentation" style={scrollStyle()}>
        <For each={items()}>
          {(item, i) => (
            <li
              role="none"
              class={item.cssClass ? `alapListElem ${item.cssClass}` : 'alapListElem'}
            >
              <a
                ref={(el) => { itemEls[i()] = el; }}
                href={sanitizeUrl(item.url)}
                target={item.targetWindow ?? 'fromAlap'}
                role="menuitem"
                tabIndex={-1}
                onMouseEnter={props.onItemHover
                  ? () => props.onItemHover!({ id: item.id, link: item, query: props.query })
                  : undefined}
                onContextMenu={props.onItemContext
                  ? (e: MouseEvent) => props.onItemContext!({ id: item.id, link: item, query: props.query, event: e })
                  : undefined}
              >
                {item.image ? (
                  <img src={sanitizeUrl(item.image)} alt={item.altText ?? `image for ${item.id}`} />
                ) : (
                  item.label ?? item.id
                )}
              </a>
            </li>
          )}
        </For>
      </Dynamic>
    );
  }

  // --- Render ---

  const triggerProps = {
    ref: (el: HTMLSpanElement) => { triggerEl = el; },
    role: 'button' as const,
    tabIndex: 0,
    'aria-haspopup': 'true' as const,
    get 'aria-expanded'() { return isOpen(); },
    get 'aria-controls'() { return isOpen() ? menuId : undefined; },
    class: props.class,
    onClick: handleTriggerClick,
    onKeyDown: handleTriggerKeyDown,
    onMouseEnter: props.onTriggerHover
      ? () => props.onTriggerHover!({ query: props.query, anchorId: props.anchorId })
      : undefined,
    onContextMenu: props.onTriggerContext
      ? (e: MouseEvent) => props.onTriggerContext!({ query: props.query, anchorId: props.anchorId, event: e })
      : undefined,
  };

  const menuContainerProps = {
    ref: (el: HTMLDivElement) => { menuEl = el; },
    id: menuId,
    role: 'menu' as const,
    'aria-labelledby': triggerId,
    get class() { return mergedMenuClassName(); },
    get style() { return mergedMenuStyle(); },
    onKeyDown: handleMenuKeyDown,
    onMouseLeave: startTimer,
    onMouseEnter: stopTimer,
  };

  if (mode() === 'popover') {
    return (
      <>
        <span {...triggerProps} popover-target={menuId}>
          {props.children}
        </span>
        <div {...menuContainerProps} popover="auto">
          <Show when={isOpen()}>
            <MenuList />
          </Show>
        </div>
      </>
    );
  }

  return (
    <span ref={(el) => { wrapperEl = el; }} style={{ position: 'relative', display: 'inline' }}>
      <span {...triggerProps}>{props.children}</span>
      <Show when={isOpen()}>
        <div {...menuContainerProps}>
          <MenuList />
        </div>
      </Show>
    </span>
  );
}
